name: Milestone Manager

on:
    pull_request_target:
        types: [milestoned]

permissions: {}

jobs:
    remove-milestone-from-unmerged-prs:
        name: "Remove Milestone from Unmerged PRs"
        if: github.event.pull_request.merged != true
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write
        steps:
            - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
              with:
                  script: |
                      github.rest.issues.update({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.payload.pull_request.number,
                          milestone: null,
                      });
