name: Highlight Rest API Changes

on:
  pull_request:
    types: [closed]

concurrency:
  group: highlight-rest-api-changes-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  send-notification-for-rest-api-changes:
    name: Send Notification for Rest API Changes
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: 'dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36'
        id: filter
        with:
          list-files: 'json'
          filters: |
            rest:
              - 'plugins/woocommerce/src/StoreApi/**'
              - 'plugins/woocommerce/src/Admin/API/**'
              - 'plugins/woocommerce/src/Utilities/RestApiUtil.php'
              - 'plugins/woocommerce/src/Internal/**/*RestApi**'
              - 'plugins/woocommerce/src/**/*RestController*'
              - 'plugins/woocommerce/includes/rest-api/**'
              - 'plugins/woocommerce/includes/*-wc-rest-*'
              
      - name: Send notification
        if: steps.filter.outputs.rest == 'true'
        uses: archive/github-actions-slack@d9dae40827adf93bddf939db6552d1e392259d7d
        id: notify
        with:
            slack-bot-user-oauth-access-token: ${{ secrets.TEST_ASSISTANCE_BOT_TOKEN }}
            slack-channel: ${{ secrets.WOO_CORE_REST_API_CHANGES_SLACK_CHANNEL }}
            slack-text: |
                <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}>
                ${{ github.event.pull_request.milestone && github.event.pull_request.milestone.html_url && github.event.pull_request.milestone.title && format('*Milestone:* <{0}|{1}>', github.event.pull_request.milestone.html_url, github.event.pull_request.milestone.title) || '' }}
                Changed files:
                ```${{ join(fromJson(steps.filter.outputs.rest_files || '[]'), '\n') }}```
            slack-optional-unfurl_links: false
            slack-optional-unfurl_media: false
