name: 'Label Pull Request Project'
on:
    pull_request_target:
        types: [opened, reopened, synchronize, ready_for_review]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
    cancel-in-progress: true

permissions: {}

jobs:
    label_project:
        # For draft PRs we'll only update labels initially, and keep updating only them after it ready for review.
        if: ${{ github.event.pull_request.draft == false || join(github.event.pull_request.labels.*.name, '') == '' }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write
        steps:
            - uses: actions/labeler@v3
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  configuration-path: .github/project-pr-labeler.yml
