name: 'Release: Enforce Code Freeze'
on:
  schedule:
    - cron: '0 18 * * *' # Every day at 18h UTC
  workflow_dispatch:

permissions: {}

env:
    GIT_COMMITTER_NAME: 'WooCommerce Bot'
    GIT_COMMITTER_EMAIL: 'no-reply@woocommerce.com'
    GIT_AUTHOR_NAME: 'WooCommerce Bot'
    GIT_AUTHOR_EMAIL: 'no-reply@woocommerce.com'

jobs:
  check-feature-freeze-event:
    name: Check for Feature Freeze events today
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.check-feature-freeze-event.outputs.should-run }}
    steps:
      - name: Install node-ical
        run: npm install node-ical
      - name: Check for Feature Freeze events today
        id: check-feature-freeze-event
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            const shouldSkipCalendarCheck = '${{ github.event_name }}' !== 'schedule';
            if (shouldSkipCalendarCheck) {
              console.log('Skip calendar event check, since the workflow was triggered manually.');
              core.setOutput('should-run', 'true');
              return;
            }

            const ical = require('node-ical');

            console.log('Checking for Feature Freeze events today...');

            try {
              const today = new Date();
              const events = await ical.async.fromURL('https://calendar.google.com/calendar/ical/${{ secrets.RELEASE_CALENDAR_ID }}/public/basic.ics');
              const dayEvents = Object.values(events)
                .filter(event => event.type === 'VEVENT')
                .filter(event => {
                  if (!event.start) return false;
                  return new Date(event.start).toDateString() === new Date(today).toDateString();
                });
              const ffEvent = dayEvents.find(event => {
                if (!event.summary) return false;
                const pattern = /^WooCommerce \d+\.\d+ Feature Freeze$/i;
                return pattern.test(event.summary);
              });
              if (ffEvent) {
                console.log(`Found Feature Freeze event: ${ffEvent.summary}`);
                core.setOutput('should-run', 'true');
              } else {
                core.setFailed('No Feature Freeze events found for today. Code freeze will not proceed.');
              }
            } catch (error) {
              core.setFailed(`Failed to fetch calendar events: ${error.message}`);
            }

  prepare-for-code-freeze:
    name: Calculate versions and confirm repo is in a good state
    needs: check-feature-freeze-event
    if: ${{ needs.check-feature-freeze-event.outputs.should-run == 'true' }}
    runs-on: ubuntu-latest
    outputs:
      nextReleaseBranch: ${{ steps.calculate-versions.outputs.nextReleaseBranch }}
      nextReleaseVersion: ${{ steps.calculate-versions.outputs.nextReleaseVersion }}
      nextTrunkVersion: ${{ steps.calculate-versions.outputs.nextTrunkVersion }}
    steps:
      - name: Verify no PRs open by the github-actions bot are open
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            const automatedPRs = await github.rest.search.issuesAndPullRequests({
              q: `repo:${context.repo.owner}/${context.repo.repo} is:pr is:open author:app/github-actions`,
            });

            if (automatedPRs.data.items.length > 0) {
              core.setFailed('There are PRs by the github-actions bot that are still open. Please merge or close before proceeding.');
              process.exit(1);
            }
      - name: Compute next release and dev cycle versions
        id: calculate-versions
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
        with:
          script: |
            const bumpMinorVersion = (v) => {
              const [major, minor, patch] = v.split('.').map(Number);
              return minor >= 9 ? `${major + 1}.0.0` : `${major}.${minor + 1}.0`
            };

            const currentRelease = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const currentVersion = currentRelease.data.tag_name.replace(/[^0-9.]+/, '');
            const nextReleaseVersion = bumpMinorVersion(currentVersion);
            const nextReleaseBranch = `release/${nextReleaseVersion.slice(0, -2)}`;
            const nextTrunkVersion = bumpMinorVersion(nextReleaseVersion);

            core.setOutput('nextReleaseVersion', nextReleaseVersion);
            core.setOutput('nextReleaseBranch', nextReleaseBranch);
            core.setOutput('nextTrunkVersion', nextTrunkVersion);

  run-code-freeze:
    name: Perform code freeze
    runs-on: ubuntu-latest
    needs: prepare-for-code-freeze
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Repo preparation to be able to use the monorepo-utils for the version bumps.
      - name: Checkout trunk
        uses: actions/checkout@v3
        with:
          ref: trunk
      - name: Setup PNPM
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d
      - name: Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
            node-version-file: .nvmrc
            cache: pnpm

      - name: Install prerequisites
        run: |
            pnpm install --filter monorepo-utils --ignore-scripts
            # ignore scripts speeds up setup significantly, but we still need to build monorepo utils
            pnpm build
        working-directory: tools/monorepo-utils

      # Actual code freeze steps.
      - name: Push frozen branch to the repo
        run: |
          # Last opportunity to bail if branch already exists.
          if [[ -n $(git ls-remote --heads origin ${{ needs.prepare-for-code-freeze.outputs.nextReleaseBranch }}) ]]; then
            echo "::error::Release branch already exists."
            exit 1
          fi

          git checkout trunk
          git checkout -b ${{ needs.prepare-for-code-freeze.outputs.nextReleaseBranch }}
          git push origin ${{ needs.prepare-for-code-freeze.outputs.nextReleaseBranch }}
      - name: Create next dev cycle milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm utils code-freeze milestone -o ${{ github.repository_owner }} -n ${{ github.event.repository.name}} -m ${{ needs.prepare-for-code-freeze.outputs.nextTrunkVersion }}
      - name: Bump versions in frozen release branch for rc.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm utils code-freeze version-bump ${{ needs.prepare-for-code-freeze.outputs.nextReleaseVersion }}-rc.1 -o ${{ github.repository_owner }} -n ${{ github.event.repository.name}} -b ${{ needs.prepare-for-code-freeze.outputs.nextReleaseBranch }}
      - name: Bump versions in trunk for next dev cycle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm utils code-freeze version-bump ${{ needs.prepare-for-code-freeze.outputs.nextTrunkVersion }}-dev -o ${{ github.repository_owner }} -n ${{ github.event.repository.name}} -b trunk

      # Notify Slack.
      - name: Notify Slack on success
        if: ${{ success() }}
        uses: archive/github-actions-slack@f530f3aa696b2eef0e5aba82450e387bd7723903 #v2.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
          slack-text: |
            :ice_cube: Code Freeze completed for `${{ needs.prepare-for-code-freeze.outputs.nextReleaseBranch }}` :checking:
            You can raise a code freeze exception if you need something to be included in this release.
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
