name: 'Release: Notify in Slack when a new (pre)release is published'
on:
  release:
    types: [published]

jobs:
  notify-release-published:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.release.tag_name, 'wc-beta-tester') }}

    steps:
      - name: 'Notify to release channel'
        uses: archive/github-actions-slack@a62d71a4ea93e68cbdc37581166b0298bea512e9 # v 2.10.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
          slack-optional-unfurl_links: false
          slack-text: |
            :woo-bounce: *<${{ github.event.release.html_url }}|WooCommerce ${{ github.event.release.name }}>* has been released! :rocket:

            (<!subteam^S086N376UTS> could you publish the release post? :ty2:)

      - name: 'Notify to announcements channel'
        uses: archive/github-actions-slack@a62d71a4ea93e68cbdc37581166b0298bea512e9 # v 2.10.0
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_ANNOUNCEMENTS_SLACK_CHANNEL }}
          slack-optional-unfurl_links: false
          slack-text: |
            :woo-bounce: *<${{ github.event.release.html_url }}|WooCommerce ${{ github.event.release.name }}>* has been released! :rocket:
