name: 'Daily checks run'
on:
  workflow_dispatch:

jobs:
  run-tests:
    name: 'Run tests'
    if: github.repository == 'woocommerce/woocommerce'
    uses: ./.github/workflows/ci.yml
    with:
      trigger: 'nightly-checks'
    secrets: inherit
